[package]
name = "broccoli"
version = "0.1.0"
edition = "2021"

[dependencies]
brain_helper = { git = "ssh://git@github.com/EMU5-Robotics/transport.git", rev = "6f7b47151a317cb21285ab585b8c741bcfb78603" }
vexide = "0.4.1"
