[package]
name = "broccoli"
version = "0.1.0"
edition = "2021"

[dependencies]
brain_helper = { git = "ssh://git@github.com/EMU5-Robotics/transport.git", rev = "019726eff048f8e092bbbf380992480c69e30b63" }
vexide = "0.4.1"
