[package]
name = "broccoli"
version = "0.1.0"
edition = "2021"

[dependencies]
brain_helper = { git = "ssh://git@github.com/EMU5-Robotics/transport.git", rev = "6cd42ff026f0bb21a8ede11f1677d3c4215980a1" }
vexide = "0.3.0"
